package com.arcamerastreamer;

/**
 * Manually created BuildConfig class.
 * Note: This is normally auto-generated by the Android Gradle Plugin.
 */
public final class BuildConfig {
    // Fields from the app's build.gradle file
    public static final boolean DEBUG = Boolean.parseBoolean("true");
    public static final String APPLICATION_ID = "com.arcamerastreamer";
    public static final String BUILD_TYPE = "debug";
    public static final int VERSION_CODE = 1;
    public static final String VERSION_NAME = "1.0";
}